### ISSUE TITLE
Open Diskstation

### ISSUE THREAD

**Issue by dwydler** [TheDuffman85/SynologyDownloadStationAdapter#2]
In the settings i activated applications url. 
I copied the displayed url into my firefox and get the erro "site not found".

**Comment by TheDuffman85** [comment]
This step is optional. If you don't want to use it, just uncheck the box.
But it means your Download Station will be opened in browser.

![help 2](https://cloud.githubusercontent.com/assets/9296618/5887309/ab3a8bfa-a3c8-11e4-8130-997188200b87.png)

If you want the Download Station to open in a dedicated window. You have to configure a application alias for it. 

![help 1](https://cloud.githubusercontent.com/assets/9296618/5887311/117c801c-a3c9-11e4-85a1-bdcdde1135f1.png)

**Comment by dwydler** [comment]
Thanks for detailed answer. Now, it work's.
