### ISSUE TITLE
https Click'n'load containers

### ISSUE THREAD

**Issue by chill0r** [TheDuffman85/SynologyDownloadStationAdapter#3]
Some sites use https for the Click'n'load Containers.

It would be good to monitor "https://+9666" too (currently only "http://+9666" is monitored)

**Comment by TheDuffman85** [comment]
Your are probably right. But I've never encountered a Click'N'Load using https. Feel free to make a pull request, I'll merge it than.

**Comment by chill0r** [comment]
I'll check it out next weekend.
It's not that simple because you can't listen to the same port twice with httpListener.
We need to use TcpListener for that.

**Comment by TheDuffman85** [comment]
Are you still planing on implement the feature or can I close this issue?

**Comment by chill0r** [comment]
Oh sorry forget to tell you - I tried to Implement it but it didn't work. I use a ghostmonkey script now to convert https click n load links to plain http links:
(Hint: The site I normally use puts the links into a form so I filter for forms but it can be canged to body if you want to use it on any site)

[ClickNLoad.user.js.txt](https://github.com/TheDuffman85/SynologyDownloadStationAdapter/files/65504/ClickNLoad.user.js.txt)
