### ISSUE TITLE
Does ist work via https connection?

### ISSUE THREAD

**Issue by stk-code** [TheDuffman85/SynologyDownloadStationAdapter#4]
I configured the downloadstation to work externally in the application portal. https://myurl:myport/download/index.cgi is reachable in my browser and uses a signed certificate.

"Open Download Station" Command opens a blank white window.
"Add Links" returns a protocol error.

**Comment by TheDuffman85** [comment]
Hello staeff777,

unfortunately HTTPS is not supported by the Download Station API. There is nothing I can do about it. It's an issue Synology has to solve.

**Comment by stk-code** [comment]
I'm sorry that I don't understand the problem yet. What aspect of the api is not support via https ?

https://myurl:myport/webapi/DownloadStation/info.cgi?api=SYNO.DownloadStation.Info&version=1&method=getinfo  is reachable.

**Comment by TheDuffman85** [comment]
All of it. The API is not reachable via HTTS. At least this was the case when I developed the tool. It might be possible now. If so, feel free to make a pull request.

**Comment by stk-code** [comment]
done.

not sure if it was due to the dependency update or if it also would be working just with the http rewrite removed in the URI Builder ( uriBuilder.Scheme = Uri.UriSchemeHttp ).
