### ISSUE TITLE
Portable Mode

### ISSUE THREAD

**Issue by ghost** [TheDuffman85/SynologyDownloadStationAdapter#6]
Hi, currently the app save the user infos in `~/AppData/Local`. It would be nice if it possible to save this infos also in the program directory.

**Comment by TheDuffman85** [comment]
Hello raschix,

this is the standard way how settings in .NET are saved. To change that I would have to implement my own settings mechanism. For me it's not worth it. But feel free to implement it your self. If you make a pull request I'll merge the code.
